# Site settings
title: Nate Green
email: hey@nategreen.design
description: > # this means to ignore newlines until "baseurl:"
  Nate Green is a UX designer with a background in visual design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nategreen.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  nategreen

# Build settings
markdown: kramdown

permalink: pretty

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      weight: 0

# Collections
# collections:
#   case-studies:
#     output: true
#     permalink: /case-studies/:path/
#     defaults:
#       - scope:
#           path: ""
#           type: case-studies
#         values:
#           layout: case-study